# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd5d9821bb7bf45cc0dffed2d8286c1e8f99bb85c74514eace29f4c96edbe768a3f7227c4c1a5bc7543ad6b3eb14b2c2e8987366302eaa6023ed38b7b5179158

test:
  secret_key_base: 1898cae7d9a5a4b9fb1061c7ed2d8df4321b174a6bd646aab6e81002d8a48299bea2f310bdc3a402b684799eec0e47dacf920240e4b2b95a2494f77ef3087ed3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
